Remove unused Member.commentCard attribute
Fixes sarumont/py-trello#80

commit 3ad3915 introduce a commentCard attribute to the Member class
which appears to be unused.

  File "trello/__init__.py", line 141, in get_member
    return Member(self, member_id).fetch()
  File "trello/__init__.py", line 1113, in fetch
    self.commentCard = json_obj['commentCard']
  KeyError: 'commentCard'